// Generated by Dagger (https://dagger.dev).
package com.hifive.sdk.dagger;

import com.hifive.sdk.controller.BaseController;
import com.hifive.sdk.service.Service;

import javax.inject.Provider;

import dagger.MembersInjector;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class BaseController_MembersInjector implements MembersInjector<BaseController> {
  private final Provider<Service> mServiceProvider;

  public BaseController_MembersInjector(Provider<Service> mServiceProvider) {
    this.mServiceProvider = mServiceProvider;
  }

  public static MembersInjector<BaseController> create(Provider<Service> mServiceProvider) {
    return new BaseController_MembersInjector(mServiceProvider);}

  @Override
  public void injectMembers(BaseController instance) {
    injectMService(instance, mServiceProvider.get());
  }

  public static void injectMService(BaseController instance, Service mService) {
    instance.mService = mService;
  }
}
