// Generated by Dagger (https://dagger.dev).
package com.hifive.sdk.dagger;

import com.hifive.sdk.repository.DataRepository;

import dagger.internal.Factory;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class DataRepository_Factory implements Factory<DataRepository> {
  private static final DataRepository_Factory INSTANCE = new DataRepository_Factory();

  @Override
  public DataRepository get() {
    return new DataRepository();
  }

  public static DataRepository_Factory create() {
    return INSTANCE;
  }

  public static DataRepository newInstance() {
    return new DataRepository();
  }
}
