// Generated by Dagger (https://dagger.dev).
package com.hifive.sdk.dagger;

import com.hifive.sdk.repository.DataRepository;
import com.hifive.sdk.service.impl.ServiceImpl;

import javax.inject.Provider;

import dagger.MembersInjector;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class ServiceImpl_MembersInjector implements MembersInjector<ServiceImpl> {
  private final Provider<DataRepository> dataRepositoryProvider;

  public ServiceImpl_MembersInjector(Provider<DataRepository> dataRepositoryProvider) {
    this.dataRepositoryProvider = dataRepositoryProvider;
  }

  public static MembersInjector<ServiceImpl> create(
      Provider<DataRepository> dataRepositoryProvider) {
    return new ServiceImpl_MembersInjector(dataRepositoryProvider);}

  @Override
  public void injectMembers(ServiceImpl instance) {
    injectDataRepository(instance, dataRepositoryProvider.get());
  }

  public static void injectDataRepository(ServiceImpl instance, DataRepository dataRepository) {
    instance.dataRepository = dataRepository;
  }
}
